export const mockAnalysisData = {
  startupName: 'MetaDEX Pro',
  chain: 'ethereum',
  timestamp: new Date().toISOString(),
  overview: {
    totalTransactions: 1245678,
    uniqueUsers: 34567,
    totalValue: '$2.3M',
    avgGas: 145,
    successRate: 98.5,
    timeRange: '7 days',
  },
  metrics: {
    tvl: [
      { name: 'Day 1', value: 850000 },
      { name: 'Day 2', value: 920000 },
      { name: 'Day 3', value: 1100000 },
      { name: 'Day 4', value: 1250000 },
      { name: 'Day 5', value: 1420000 },
      { name: 'Day 6', value: 1680000 },
      { name: 'Day 7', value: 2300000 },
    ],
    rates: [
      { name: 'Mon', borrowing: 3.2, lending: 2.1 },
      { name: 'Tue', borrowing: 3.4, lending: 2.3 },
      { name: 'Wed', borrowing: 3.1, lending: 2.0 },
      { name: 'Thu', borrowing: 3.8, lending: 2.5 },
      { name: 'Fri', borrowing: 3.5, lending: 2.2 },
      { name: 'Sat', borrowing: 3.9, lending: 2.6 },
      { name: 'Sun', borrowing: 4.1, lending: 2.8 },
    ],
    ratios: [
      { name: 'VolumeToTVL', value: 45 },
      { name: 'FeeToVolume', value: 25 },
      { name: 'RewardCost', value: 18 },
      { name: 'Slippage', value: 12 },
    ],
    dau: 8420,
    mau: 34567,
    activePools: 156,
    crossChain: 24,
  },
  users: {
    behavior: [
      { name: 'Whale', value: 5, fill: '#6B7280' },
      { name: 'Bot', value: 12, fill: '#4B5563' },
      { name: 'PowerUser', value: 28, fill: '#9CA3AF' },
      { name: 'NewUser', value: 55, fill: '#D1D5DB' },
    ],
    scores: [
      { metric: 'Loyalty', score: 8.5 },
      { metric: 'Retention', score: 7.8 },
      { metric: 'Growth', score: 9.2 },
      { metric: 'Churn', score: 4.3 },
    ],
    topUsers: [
      { address: '0x1234...5678', txCount: 1203, value: '$450K' },
      { address: '0xabcd...ef01', txCount: 956, value: '$380K' },
      { address: '0x5678...9abc', txCount: 834, value: '$295K' },
      { address: '0xdef0...1234', txCount: 645, value: '$210K' },
      { address: '0x9abc...def0', txCount: 512, value: '$165K' },
    ],
  },
  transactions: {
    data: [
      { hash: '0xabc...', from: '0x123...', to: '0x456...', value: '$1200', gas: 145, status: 'success' },
      { hash: '0xdef...', from: '0x789...', to: '0xabc...', value: '$450', gas: 127, status: 'success' },
      { hash: '0x123...', from: '0x456...', to: '0xdef...', value: '$2100', gas: 156, status: 'failed' },
      { hash: '0x456...', from: '0x789...', to: '0x123...', value: '$890', gas: 139, status: 'success' },
      { hash: '0x789...', from: '0xabc...', to: '0x456...', value: '$560', gas: 151, status: 'success' },
    ],
    volumeTimeline: [
      { day: 'Day 1', volume: 125000 },
      { day: 'Day 2', volume: 148000 },
      { day: 'Day 3', volume: 167000 },
      { day: 'Day 4', volume: 192000 },
      { day: 'Day 5', volume: 215000 },
      { day: 'Day 6', volume: 248000 },
      { day: 'Day 7', volume: 289000 },
    ],
  },
  competitive: {
    marketPosition: { share: 22, rank: 3 },
    advantages: [
      'Lower gas costs (145 avg vs 180 competitors)',
      'Higher success rate (98.5% vs 94% avg)',
      'Faster execution (2.1s avg vs 3.2s)',
      'Better user retention (7.8 score)',
    ],
    challenges: [
      'Limited liquidity pools (156 vs 300+ leaders)',
      'Newer ecosystem (6 months old)',
      'Smaller TVL ($2.3M vs $45M leaders)',
      'Limited cross-chain integration',
    ],
    benchmarks: [
      { metric: 'Gas Efficiency', you: 85, ethereum: 60 },
      { metric: 'Speed', you: 92, ethereum: 65 },
      { metric: 'Growth', you: 88, ethereum: 70 },
    ],
  },
  recommendations: [
    '🚀 Expand liquidity incentives to attract whale traders',
    '⚙️ Optimize gas consumption for micro-transactions',
    '🌍 Launch cross-chain bridge with Polygon and Arbitrum',
    '📊 Implement dynamic fee structure based on demand',
  ],
  alerts: [
    { severity: 'warning', message: 'TVL declined 2.3% in last 24 hours' },
    { severity: 'info', message: 'New competitor launched on same chain' },
  ],
};